### ISSUE TITLE
HTML rendering configuration

### ISSUE THREAD

**Issue by mjfryc** [mjfryc/mjaron-etudes-java#17]
Add `htmlId(String)` and `htmlClass(String)` for HTML rendering, e.g:

```java
Table.render(...).html(htmlId("myTable")).run();
```

It will allow to configure the table view out of this library.

```css
table#myTable tr:nth-child(1) td{ background:green; }

#myTable tr td:nth-child(3) {
  background:orange;
}
```
